### ISSUE TITLE
Feel free to modularize my Russian language project | EDIT: Never mind, I forked. Please close me :))

### ISSUE THREAD

**Issue by dmitripot** [e107inc/e107-v2.x-Language-Packs#12]
Fluent Russian speaker here. Also working a community that's going through the 1.x to 2.0 switch for e107. Tons of Russians. Even if I miss something, they wont. :P

Also, if I ever stop updating, you could always just copy my repo back locally into e107-v2.x-Language-Packs. It's under GPL. But yeah, anyways: http://github.com/dmitripot/e107-russian-translation

**Comment by Jimmi08** [comment]
Hi, I wanted to ask you about this when I found your repository yesterday.  If only way how to do it is via request, I can use my repo for this. I will need Russian translation too.

**Comment by dmitripot** [comment]
Well there are two options from the looks of it. The most advised and "proper" solution is to have a forked version of a Git repo., work on it, and request pulls to owners of master branch. The way that the e107 team did it for Bulgarian is they simply modularized the Bulgarian/ subdirectory from another user.

I wanted the modularized method because I looked at the already existing (about a dozen) forks, and got scared :P

**Comment by dmitripot** [comment]
I just realized that the description for this repo says "Feel free to contribute by pull request". I made a fork ( dmitripot/e107-v2.x-Language-Packs ). Pull request made. Validates as of Jan 17 GitHub version of e107.
